### ISSUE TITLE
Would be great if it have an online features demonstration page

### ISSUE THREAD

**Issue by JosielFaleiros** [stelace/sharinplace#6]

**Comment by abruere** [comment]
We’re working on a public demo showcasing our new API. We really focus on the API right now, rather than interface.

Meanwhile, here is what we’ve done with an old version of Stelace codebase in the past: [https://sharinplace.fr](https://sharinplace.fr).

I will close this issue once the new demo is available.

Thanks!

**Comment by abruere** [comment]
Closing this as we've just released a demo UI of our API's: https://marketplace.demo.stelace.com ([github](https://github.com/stelace/marketplace-demo))

I hope this can help!
